// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

// Injectors from wire.go:

func injectedResult() Result {
	s := provideS()
	string2 := s.Foo
	int2 := s.Bar
	result := provideResult(string2, int2)
	return result
}
